# Generated by Django 5.0 on 2024-02-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_admin123'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin123',
            table='tbl123',
        ),
    ]
