# Generated by Django 5.0 on 2024-02-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_alter_admin123_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'studentdetails',
            },
        ),
        migrations.DeleteModel(
            name='Admin123',
        ),
    ]
