# Generated by Django 5.0 on 2024-02-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_studentdetails_delete_admin123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentdetails',
        ),
    ]
