# Generated by Django 5.0 on 2024-02-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_alter_admin_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='ttmadmin_table',
        ),
    ]
